name: reducer_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.7 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.1
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.3

flutter:
  uses-material-design: true
